### PR TITLE
build-essential dependency loosened

### PR DESCRIPTION
**Pull request by atheiman**
kitchen tested with build-essential 2.4.0: https://gist.github.com/atheiman/ee546e8dee4c556093150ae75431e156

### CODE REVIEW

**Comment by spion06** [comment]
+1 assuming tests pass

**Comment by atheiman** [comment]
I have no idea what the chefspec tests fail on travis, here it is fine locally

```
[chefvm stage_dr] simple-passenger-cookbook $ bundle exec rspec

simple_passenger::default
  When all attributes are default, on an unspecified platform
[2016-11-04T14:46:57-05:00] WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at /Users/ah033384/ets/simple-passenger-cookbook/spec/unit/recipes/default_spec.rb:13:in `block (4 levels) in <top (required)>'
[2016-11-04T14:46:58-05:00] WARN: method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at /Users/ah033384/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-12.13.37/lib/chef/node/attribute.rb:520:in `method_missing' at /Users/ah033384/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-12.13.37/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
    converges successfully

Finished in 7.06 seconds (files took 2.99 seconds to load)
1 example, 0 failures


ChefSpec Coverage report generated...

  Total Resources:   14
  Touched Resources: 0
  Touch Coverage:    0.0%

Untouched Resources:

  execute[restart app]               simple_passenger/recipes/default.rb:28
  execute[stop app]                  simple_passenger/recipes/default.rb:39
  group[passenger group]             simple_passenger/recipes/default.rb:50
  user[passenger user]               simple_passenger/recipes/default.rb:54
  directory[app log dir]             simple_passenger/recipes/default.rb:61
  directory[pid dir]                 simple_passenger/recipes/default.rb:81
  directory[app dir]                 simple_passenger/recipes/default.rb:90
  package[git]                       simple_passenger/recipes/default.rb:99
  git[app]                           simple_passenger/recipes/default.rb:100
  template[passengerfile]            simple_passenger/recipes/default.rb:110
  ruby_build_ruby[app ruby version 2.2.5]   simple_passenger/recipes/default.rb:137
  gem_package[bundler]               simple_passenger/recipes/default.rb:143
  execute[bundle install]            simple_passenger/recipes/default.rb:155
  execute[start app]                 simple_passenger/recipes/default.rb:165
```

**Comment by atheiman** [comment]
ehh something in a dependency is broke... i found another job on travis fail recently with the same thing https://travis-ci.org/schubergphilis/nagios

so i updated my bundle locally and tested again and tests failed with the same issue. im gonna say this is fine for now.

**Comment by edwlarkey** [comment]
@atheiman that sounds good to me. +1

**Comment by atheiman** [comment]
lol i do that every damn time

**Pull request closed without merging**
